name: Deploy ARM Template

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: "ResourceofJoy" # Replace with your actual Resource Group name
          template: ./azuredeploy.json
          parameters: storageAccountName="mystorageacct2026xyz" # Must be globally unique!
          failOnStdErr: false
